--table creation



CREATE TABLE "user" (

id SERIAL PRIMARY KEY,  
firstName VARCHAR(100) NOT NULL, 
lastName VARCHAR(100) NOT NULL, 
email VARCHAR(255) UNIQUE NOT NULL, 
password TEXT NOT NULL, 
refreshToken TEXT NOT NULL,
isActive BOOLEAN NOT NULL DEFAULT TRUE, 
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



