ALTER TABLE "user"
  ALTER COLUMN firstName DROP NOT NULL,
  ALTER COLUMN lastName DROP NOT NULL,
  ALTER COLUMN email DROP NOT NULL,
  ALTER COLUMN password DROP NOT NULL,
  ALTER COLUMN refreshToken DROP NOT NULL;