


CREATE TABLE merchant (

id SERIAL PRIMARY KEY,  
merchantName VARCHAR(100), 
isActive BOOLEAN NOT NULL DEFAULT TRUE, 
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "user" ADD merchantId INT REFERENCES merchant(id) ON DELETE CASCADE;
