
DELETE http://localhost:4000/api/logout
# Authorization: Bearer 
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImlhdCI6MTc1MTU2NzY4MiwiZXhwIjoxNzU0MTU5NjgyfQ.BwZku3IrwmZ5eSZMy4yx9wX0k9tmV-zMxuHUdL4EWhs"
}

###

POST http://localhost:4000/api/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDEsImlhdCI6MTc1MTU2NzY4MiwiZXhwIjoxNzU0MTU5NjgyfQ.BwZku3IrwmZ5eSZMy4yx9wX0k9tmV-zMxuHUdL4EWhs"
}

####

POST http://localhost:4000/api/login
Content-Type:  application/json

{
    "email": "elie@something.com",
    "password" : "password1"
}


###

POST http://localhost:4000/api/register
Content-Type: application/json

{
    "firstName": "",
    "lastName" : "",
    "email": "",
    "password": ""
}
