
DELETE http://localhost:4000/api/logout
# Authorization: Bearer 
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsImlhdCI6MTc1MTg4MzgyOCwiZXhwIjoxNzU0NDc1ODI4fQ.06hwskEPVsMbiGq-rAeT8fie0xVK7MqfyGlcEqEVYYk"
}

###

POST http://localhost:4000/api/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsImlhdCI6MTc1MTg4MzgyOCwiZXhwIjoxNzU0NDc1ODI4fQ.06hwskEPVsMbiGq-rAeT8fie0xVK7MqfyGlcEqEVYYk"
}

####

POST http://localhost:4000/api/login
Content-Type:  application/json

{
    "email": "yes@something.com",
    "password" : "password"
}


###

POST http://localhost:4000/api/register
Content-Type: application/json

{
    "firstName": "yes",
    "lastName" : "ar",
    "email": "yes@something.com",
    "password": "password",
    "merchantId": 2
}
