GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsImlhdCI6MTc1MTUzNzg3NCwiZXhwIjoxNzUxNTM3OTA0fQ.aRPBR6ZF5iI7TTsm0AROEgz48sjKGhsw_ja52ofcpRw

###

DELETE http://localhost:4000/api/logout
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlhdCI6MTc1MTQ1OTU0MSwiZXhwIjoxNzUxNDU5NTcxfQ.iTwbWVtJOWiquxbI6lA4TCJFnRMSKrVuzcVnDzHtDa0
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsImlhdCI6MTc1MTUzNzY1MCwiZXhwIjoxNzU0MTI5NjUwfQ.olZQNCX0o9LYLy5UP-NpqwlALGE79IvjNOOuV5JjGZo"
}

###

POST http://localhost:4000/api/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsImlhdCI6MTc1MTUzNzY1MCwiZXhwIjoxNzU0MTI5NjUwfQ.olZQNCX0o9LYLy5UP-NpqwlALGE79IvjNOOuV5JjGZo"
}

####

POST http://localhost:4000/api/login
Content-Type:  application/json

{
    "email": "yara@something.com",
    "password" : "pass"
}


###

POST http://localhost:4000/api/register
Content-Type: application/json

{
    "firstName": "yara",
    "lastName" : "AR",
    "email": "yara@something.com",
    "password": "pass"
}
