GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTc1MTQ1MzUwMCwiZXhwIjoxNzUxNDUzNTMwfQ.XL5AgQ6g0WkExWJebRKqKJ5R-NS6W_JtfEQ7GZGEvKo

###

DELETE http://localhost:4000/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTc1MTQ1MzUwMCwiZXhwIjoxNzUxNDUzNTMwfQ.XL5AgQ6g0WkExWJebRKqKJ5R-NS6W_JtfEQ7GZGEvKo
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTc1MTQ1MzM2OCwiZXhwIjoxNzU0MDQ1MzY4fQ.pcxKptk4nDNQCTO_rWMRRMYZFLt_YpEExWDqgq9v4YU"
}

###

POST http://localhost:4000/api/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTc1MTQ1MzM2OCwiZXhwIjoxNzU0MDQ1MzY4fQ.pcxKptk4nDNQCTO_rWMRRMYZFLt_YpEExWDqgq9v4YU"
}

####

POST http://localhost:4000/api/login
Content-Type:  application/json

{
    "email": "larry@something.com",
    "password" : "pass"
}


###

POST http://localhost:4000/api/register
Content-Type: application/json

{
    "firstName": "larry",
    "lastName" : "AR",
    "email": "larry@something.com",
    "password": "pass"
}
